### ISSUE TITLE
AWX settings where migarted, except passwords. Update those manually.

### ISSUE THREAD

**Issue by nicolaibaralmueller** [autops/awx-migrate#10]
I've been trying to setup access to awx docker postgres which finally worked after maaa...aaany hours.

I was so excited to watch the execution process and when viewing the json files no credentials are to be seen. Only the Demo Credential. Oh, and yes, I've added dummy credentials for testing purposes.

Message is:
AWX settings where migarted, except passwords. Update those manually.

And I wonder why I used so many hours on this :) 

Tower 4.0
Ansible 2.7.10
Tower-Cli 3.4.3

**Comment by nicolaibaralmueller** [comment]
lo and behold... it worked after new tower-cli session.

**Comment by srgvg** [comment]
That message is specific about the awx settings (e.g. ldap settings) which are not accessible via the api. It can migrate those settings, but I couldn't find how to decrypt the ldap password.

**Comment by nicolaibaralmueller** [comment]
I've modifed the AUTH_LDAP_BIND_PASSWORD but the script still says:

> Wrong encryption key for config field AUTH_LDAP_BIND_PASSWORD, you will need to update this manually.

@srgvg So this is a known error?

Also, when trying to send the received data to a new server it complains about missing users.

> Asset of type user is missing identifier field username
Asset of type user is missing identifier field username
Asset of type user is missing identifier field username
Asset of type user is missing identifier field username
Asset of type user is missing identifier field username
Error: One or more errors encountered in provided assets, stopping import


I guess this is caused by using ldap users? So we have to set the ldap settings on the awx host first and add users before we can import?

Thanks

**Comment by srgvg** [comment]
Hi @nicolaibaralmueller 

First, abouth the LDAP password, not sure what you mean when you say you modified it. The script just gives you a warning that it cannot decrypt it, as I didn't find out how to decrypt paswords in the settings table of the database. I only managed to do that for secrets, so the script will always warn about this. Not a biggie, as that is just one password you have to update manually in the new setup.

Secondly, the thing you see about missing users might be something I encountered myself:

LDAP users do get referenced locally in the AWX database, and I'm not sure how AWX identifies them as LDAP users. IIRC the password field got filled with something special, but I'm not sure.

This leads to a kind of chicken and egg problem:

- When you import all users, the LDAP users get imported as regular users, and AWX doesn't link them again to the LDAP user, which leads to the user  not being able to log in.
- If you don't import the user, you'll get errors on other objects (like groups, or object ownerships) that reference the user.

What I did in the end was:
- import all users and other objects
- delete the user, and have them log in again so it gets recreated in the database
- manually add the user back to certain groups (if this doesn't get handled automatically by ldap group mappings)

Also, in early versions of AWX (pre 1.0) I recall there was a problem with tower-cli not exporting the users, or at least not with all their needed parameters, which lead to a similar error.

Hope this helps,

Serge

**Comment by nicolaibaralmueller** [comment]
@srgvg 

I understand and you are right. LDAP users import will conflict with actual ldap because of passwords. Only way to do this was to export users normally with tower-cli and the import. 

Your script is awesome!

**Comment by srgvg** [comment]
Thank you!

**Comment by bwahmed** [comment]
I'm getting this error 
Asset of type user is missing identifier field username
I'm not using LDAP. Any clues of what I'm doing wrong?
