### ISSUE TITLE
Add jq to list of requirements.

### ISSUE THREAD

**Issue by dustinmhorvath** [autops/awx-migrate#5]
Installation of `jq` using pip failed to build using wheel. I ended up sideloading a binary from [here](https://github.com/stedolan/jq/releases/) and copying into /usr/bin so that it would be in my path. Testing on Rhel7. `jq` is likely available through epel, but that repo wasn't immediately available in our environment.

Installation of the other requirements using the pipfile worked without issue.

**Comment by srgvg** [comment]
I install `jq` from my OS package manager, and that is not a Python application (upstream is indeed https://github.com/stedolan/jq). Python https://pypi.org/project/jq/ are Python bindings to jq, so two different things. I presume you could prolly `yum install jq`? Anyway, `jq` is not a Python dependency to the `awx-migrate` script, only to the wrapper bash script.

Thanks for trying out the script. Let me know how that goes.
